### ISSUE TITLE
Reconciling string.h

### ISSUE THREAD

**Issue by jaspersong** [kachmarma/cs4500-a1-p2#10]
We are currently reconciling string.h interfaces between our 3 spec teams. We have decided that string.h needs two additional functions:
```
        //compare this string to another one based on lexicographical order
        int compareTo(String* other);

        //print this string
        void print();
```

In addition, please update the name of size() to length() in order to match the other interfaces.

Thank you.

**Comment by thomas-vaiarella** [comment]
Hi Joe! Due to multiple requests for reconciliation, we plan on modifying our object.h and string.h interfaces as per this Piazza post and repo: https://piazza.com/class/k51bluky59n2jr?cid=345 https://github.com/chasebish/cwc_object_string

If you are able to talk to your other spec teams to due the same, then we will all be able to reach a quorum. Let me know what you think.

**Comment by jaspersong** [comment]
Yep, we saw that post, and are currently updating our own repo to match with that spec as well, along with talking to the other teams we are working with to match. So once that update gets pushed onto your repo, we should be good to go.
