### ISSUE TITLE
Suggestion (Reconcile)

### ISSUE THREAD

**Issue by ZiyiPeng** [kachmarma/cs4500-a1-p2#11]
Hi teams! I think it is important to reach an agreement on Object.h and String.h. I think the easiest way is to only include the most basic functionalities in those files, as long as they are enough for this assignment. 
I suggest we have the following methods in object and string class. At first glance, these should be enough to finish this assignment. 
object:
virtual size_t hash()
virtual bool equals(Object* object)

String:
int compare_to()
String* concat(String* other)

**Comment by thomas-vaiarella** [comment]
Hi Tom! Due to multiple requests for reconciliation, we plan on modifying our object.h and string.h interfaces as per this Piazza post and repo: https://piazza.com/class/k51bluky59n2jr?cid=345 https://github.com/chasebish/cwc_object_string

If you are able to talk to your other spec teams to due the same, then we will all be able to reach a quorum. Let me know what you think.

**Comment by jaspersong** [comment]
Closed [a related issue](https://github.com/kachmarma/cs4500-a1-p2/issues/10) in favor of the discussion thread post here. I agree that we should be matching ourselves with the class piazza post standard.

**Comment by kachmarma** [comment]
This should be done. Let me know if you have any further questions / concerns. Closing issue for now.
